# 글로벌 설정
#polling_interval: 60
#polling_delay: 0
#dispatch_interval: 1
#task_check_interval: -1
#page_size: 100
#ignore_folder: true
#patterns: [.*]
#ignore_patterns: ['\.((json|bak|mpd|log|git/?)$|log\.)', '[/\\](\..+|bonus|extra|featurette|other|sample|screenshot|trailer|\[업로드\])s?']
#actions:
#buffer_interval: 30

google_drive:
  token:
    client_id: "123456789012-1234abcd5678efgh9012ijk3456lmno7.apps.googleusercontent.com"
    client_secret: "ABCDEF-a1b2c3d4e5f6g7h8j9k0l1m2n3o4"
    refresh_token: "1//0a1b2c3d4f5g6h7i8j9k0l1m2n3o-4p5q6r7s8t9u0v1w2x-3y4z5a6b7c8d-9e0f1g2h3i4j5k6l7m-8n9o0p1q2r3s4t5u6v7w"
    #token: 'ya11.abcdef...j34kl'
  scopes:
    - "drive.readonly"
    - "drive.activity.readonly"
#  cache_enable: false
#  cache_ttl: 600 # seconds
#  cache_maxsize: 64 # each

#logging:
#  level: debug
#  format: '%(asctime)s,%(msecs)03d|%(levelname)-8s %(message)s ... %(filename)s:%(lineno)d'
#  date_format: '%Y-%m-%dT%H:%M:%S'
#  redacted_patterns:
#    - "apikey=(.{10,36})"
#    - "['\"]apikey['\"]: ['\"](.{10,36})['\"]"
#    - "['\"]X-Plex-Token['\"]: ['\"](.{20})['\"]"
#    - "['\"]X-Plex-Token=(.{20})['\"]"
#    - "webhooks/(.+)/(.+):\\s{"
#  redacted_substitute: "<REDACTED>"

pollers:
  - name: "단순 로그"
    targets:
      - "폴더_ID#/path/to/be/resolved"
    dispatchers:
      - class: DummyDispatcher

  - name: "plex_mate"
    targets:
      - "폴더_ID#/mnt/gds/GDRIVE/VIDEO/방송중"
    ignore_folder: false
    dispatchers:
      - class: PlexmateDispatcher
        url: "http://flaskfarm:9999"
        apikey: "ABCDEFGHI9"
        mappings:
          - "/mnt/gds/GDRIVE:/host/mnt/gds/GDRIVE"
#  - name: '디스코드 알람용'
#    targets:
#      - '폴더_ID#/mnt/gds/GDRIVE/VIDEO/방송중'
#    dispatchers:
#      - class: DiscordDispatcher
#        # https://discord.com/api/webhooks/{webhook_id}/{webhook_token}
#        webhook_id: '1234567890123456789'
#        webhook_token: 'abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz123456'
#        colors:
#          # https://gist.github.com/thomasbnt/b6f455e2c7d743b796917fa3c205f812
#          default: '0'
#          move: '3447003'
#          create: '5763719'
#          delete: '15548997'
#          edit: '16776960'

#  - name: '카비타 스캔용'
#    targets:
#      - '폴더_ID#/mnt/gds2/GDRIVE/READING/만화'
#    dispatchers:
#      - class: RcloneDispatcher
#        url: 'http://user:pass@172.17.0.1:5574#gds2'
#        mappings:
#          - '/mnt/gds2/GDRIVE:/GDRIVE'
#      - class: KavitaDispatcher
#        url: 'http://kavita:5000'
#        apikey: '123abcde-001f-002g-003h-ijklmnop0987'

#  - name: '여러 Rclone RC 및 plex 서버를 한번에 지정할 경우'
#    targets:
#      - '폴더_ID#/mnt/gds/GDRIVE/VIDEO/방송중'
#    dispatchers:
#      - class: MultiPlexRcloneDispatcher
#        buffer_interval: 60
#        rclones:
#          - url: 'http://username:password@localhost:5275'
#            mappings:
#              - '/host1/gds/GDRIVE:/GDRIVE'
#        plexes:
#          - url: 'http://plex-1:32400'
#            token: '1bCdEfG0HiJkLmNoP2Qr'
#            mappings:
#              - '/GDRIVE:/plex1/gds2/GDRIVE'
#          - url: 'http://plex-2:32400'
#            token: '2bCdEfG0HiJkLmNoP2Qr'
#            mappings:
#              - '/GDRIVE:/plex2/gds2/GDRIVE'
#          - url: 'http://plex-3:32400'
#            token: '3bCdEfG0HiJkLmNoP2Qr'
#            mappings:
#              - '/GDRIVE:/plex3/gds2/GDRIVE'

#  - name: '쉘 커맨드 실행용'
#    targets:
#      - '폴더_ID#/MY_DRIVE'
#    dispatchers:
#      - class: CommandDispatcher
#        command: 'python3 /data/command/file-process.py'
#        wait_for_process: false
#        drop_during_process: false
#        timeout: 60
#        mappings:
#          - '/MY_DRIVE:X:/downloads'
